on:
    push:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2

            - name: Install Dependencies
              run: bun install

            - name: Vite Build
              run: bun run build

            - name: Upload GitHub Pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: dist/

    deploy:
        runs-on: ubuntu-latest
        needs: build

        permissions:
            pages: write
            id-token: write

        steps:
            - name: Deploy GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
